export const mentors = [
  {
    id: 1,
    name: "John Doe",
    expertise: "Digital Marketing",
    available: true,
    is_premium: true,
    slots: ["19:00", "19:30", "20:00"],
  },
  {
    id: 2,
    name: "Jane Smith",
    expertise: "FMCG Sales",
    available: true,
    is_premium: false,
    slots: ["18:00", "18:30", "19:00"],
  },
  {
    id: 3,
    name: "Alice Johnson",
    expertise: "Equity Research",
    available: false,
    is_premium: false,
    slots: [],
  },
  {
    id: 4,
    name: "Michael Brown",
    expertise: "Human Resources",
    available: true,
    is_premium: false,
    slots: ["17:00", "17:30", "18:00"],
  },
  {
    id: 5,
    name: "Emily Davis",
    expertise: "Project Management",
    available: true,
    is_premium: true,
    slots: ["18:30", "19:00", "19:30"],
  },
  {
    id: 6,
    name: "Chris Wilson",
    expertise: "Finance",
    available: true,
    is_premium: false,
    slots: ["19:00", "19:30", "20:00"],
  },
  {
    id: 7,
    name: "Patricia Taylor",
    expertise: "Operations Management",
    available: false,
    is_premium: false,
    slots: [],
  },
  {
    id: 8,
    name: "James Anderson",
    expertise: "Data Science",
    available: true,
    is_premium: true,
    slots: ["20:00", "20:30", "21:00"],
  },
  {
    id: 9,
    name: "Linda Thomas",
    expertise: "Digital Marketing",
    available: true,
    is_premium: false,
    slots: ["19:00", "19:30", "20:00"],
  },
  {
    id: 10,
    name: "Robert Harris",
    expertise: "FMCG Sales",
    available: true,
    is_premium: false,
    slots: ["17:00", "17:30", "18:00"],
  },
  {
    id: 11,
    name: "Jennifer Martin",
    expertise: "Supply Chain Management",
    available: true,
    is_premium: true,
    slots: ["20:00", "20:30", "21:00"],
  },
  {
    id: 12,
    name: "Charles Lee",
    expertise: "Equity Research",
    available: true,
    is_premium: false,
    slots: ["19:00", "19:30", "20:00"],
  },
  {
    id: 13,
    name: "Susan Walker",
    expertise: "Business Analytics",
    available: true,
    is_premium: false,
    slots: ["18:00", "18:30", "19:00"],
  },
  {
    id: 14,
    name: "Daniel Hall",
    expertise: "E-Commerce",
    available: true,
    is_premium: true,
    slots: ["20:00", "20:30", "21:00"],
  },
  {
    id: 15,
    name: "Jessica Young",
    expertise: "Digital Marketing",
    available: true,
    is_premium: false,
    slots: ["19:00", "19:30", "20:00"],
  },
];

export const durations = [
  { label: "30 minutes", price: 2000 },
  { label: "45 minutes", price: 3000 },
  { label: "60 minutes", price: 4000 },
];

export const areasOfInterest = [
  { label: "Digital Marketing", value: "Digital Marketing" },
  { label: "FMCG Sales", value: "FMCG Sales" },
  { label: "Equity Research", value: "Equity Research" },
  { label: "Human Resources", value: "Human Resources" },
  { label: "Project Management", value: "Project Management" },
  { label: "Finance", value: "Finance" },
  { label: "Operations Management", value: "Operations Management" },
  { label: "Data Science", value: "Data Science" },
  { label: "Supply Chain Management", value: "Supply Chain Management" },
  { label: "Business Analytics", value: "Business Analytics" },
  { label: "E-Commerce", value: "E-Commerce" },
];
